# Generated by Django 4.2.30 on 2026-07-01 11:17

from django.db import migrations, models
import django.db.models.deletion


SOURCE_SITE_DEFAULTS = (
    ("docdoc", "DocDoc", "https://docdoc.ru"),
    ("doctu", "Doctu", "https://doctu.ru"),
    ("napopravku", "НаПоправку", "https://napopravku.ru"),
    ("prodoctorov", "ПроДокторов", "https://prodoctorov.ru"),
)


def forwards_populate_sites(apps, schema_editor):
    SourceSite = apps.get_model("reviews", "SourceSite")
    DoctorSource = apps.get_model("reviews", "DoctorSource")

    source_map = {}
    for code, name, base_url in SOURCE_SITE_DEFAULTS:
        source_map[code], _ = SourceSite.objects.get_or_create(
            code=code,
            defaults={
                "name": name,
                "base_url": base_url,
                "parser_key": code,
            },
        )

    for source in DoctorSource.objects.all():
        site = source_map.get(source.source_site)
        if site:
            source.site_id = site.id
            source.save(update_fields=["site"])


def backwards_clear_sites(apps, schema_editor):
    DoctorSource = apps.get_model("reviews", "DoctorSource")
    SourceSite = apps.get_model("reviews", "SourceSite")
    DoctorSource.objects.update(site=None)
    SourceSite.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('base_url', models.URLField(blank=True)),
                ('parser_key', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('use_browser_fallback', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='doctorsource',
            options={'ordering': ['crawl_priority', 'source_site', 'profile_url']},
        ),
        migrations.AddField(
            model_name='doctorsource',
            name='consecutive_failures',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctorsource',
            name='crawl_priority',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='doctorsource',
            name='last_http_status',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorsource',
            name='last_reviews_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctorsource',
            name='last_success_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorsource',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorsource',
            name='last_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ok', 'OK'), ('failed', 'Failed'), ('blocked', 'Blocked'), ('skipped', 'Skipped')], default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='doctorsource',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doctor_sources', to='reviews.sourcesite'),
        ),
        migrations.RunPython(forwards_populate_sites, backwards_clear_sites),
        migrations.AddConstraint(
            model_name='doctorsource',
            constraint=models.UniqueConstraint(condition=models.Q(('site__isnull', False)), fields=('site', 'profile_url'), name='uniq_site_profile'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('doctor_source', 'external_id'), name='uniq_review_external_id'),
        ),
    ]
