# Generated by Django 4.2.30 on 2026-07-01 11:48

from django.db import migrations, models


def forwards_fill_fields(apps, schema_editor):
    Doctor = apps.get_model("reviews", "Doctor")
    SourceSite = apps.get_model("reviews", "SourceSite")

    for doctor in Doctor.objects.all():
        parts = [part for part in (doctor.full_name or "").split() if part]
        if len(parts) >= 3 and not doctor.middle_name:
            doctor.last_name = doctor.last_name or parts[0]
            doctor.first_name = doctor.first_name or parts[1]
            doctor.middle_name = " ".join(parts[2:])
            doctor.save(update_fields=["last_name", "first_name", "middle_name"])

    SourceSite.objects.filter(code__in=["docdoc", "doctu"]).update(manual_browser_assist=True)


def backwards_fill_fields(apps, schema_editor):
    SourceSite = apps.get_model("reviews", "SourceSite")
    SourceSite.objects.update(manual_browser_assist=False)


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_sourcesite_alter_doctorsource_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='middle_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='sourcesite',
            name='manual_browser_assist',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(forwards_fill_fields, backwards_fill_fields),
    ]
