# Generated by Django 4.2.30 on 2026-07-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_pipelinejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinejob',
            name='blocked_sources',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pipelinejob',
            name='current_doctor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pipelinejob',
            name='current_profile_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='pipelinejob',
            name='current_source_site',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='pipelinejob',
            name='current_stage',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='pipelinejob',
            name='failed_sources',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pipelinejob',
            name='processed_sources',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pipelinejob',
            name='recent_events',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pipelinejob',
            name='scope',
            field=models.CharField(choices=[('all', 'All Sources'), ('manual_blocked', 'Manual Blocked Queue')], default='all', max_length=32),
        ),
        migrations.AddField(
            model_name='pipelinejob',
            name='skipped_sources',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pipelinejob',
            name='success_sources',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pipelinejob',
            name='total_sources',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
